name: test-release

on:
  push:
    branches:
      - "dev**"

jobs:
  build-and-publish:
    name: Build and publish Python distributions TestPyPI
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

      - name: Install pypa/build
        run: >-
          python -m
          pip install
          build
          --user

      - name: Build a binary wheel and a source tarball
        run: >-
          python -m
          build
          --config-setting=--global-option=egg_info
          --config-setting=--global-option=--tag-build="-$(date +"%Y%m%d%H%M%S")"
          --sdist
          --wheel
          --outdir dist/
          .

      - name: Publish distribution package to TestPyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/
